### ISSUE TITLE
Handle QEMU process being abruptly ended

### ISSUE THREAD

**Issue by tvelocity** [virtualopensystems/linux-kvm-arm#12]
Reported by Peter Maydell:

Currently if you ^C the qemu process then instead of a nice
clean exit things go a bit pear shaped, with apparently part
of the qemu/kvm combo having quit and the rest not and lots
of error messages being emitted.

**Comment by chazy** [comment]
I'm not exactly sure what the problem here is. As I can see, QEMU catches SIGINT for whatever purposes and doesn't quit. However, doing c+a, x  cleanly kills the process and shuts everything down nicely.

I can look more into what SIGINT is exactly supposed to perform, but I don't see what we are not doing that the other KVM archs are doing...?
