### ISSUE TITLE
support running KVM enabled kernel as a guest

### ISSUE THREAD

**Issue by pm215** [virtualopensystems/linux-kvm-arm#16]
At the moment if you try to run a KVM-enabled kernel as a KVM guest, it dies at the point where the guest kernel tries to do an SMC to install its hyp vector. We should gracefully deduce that we're not running on a virtualization-capable system instead.

As I understand it the plan was:
- boot wrapper boots kernel in Hyp mode (it does this now)
- kernel looks at what mode it was started in
- if Hyp mode, save a backdoor so we can regain privs later, drop down to supervisor mode and continue booting
- if supervisor mode, make a note that we don't have hyp access
- later when kvm is started (possibly after module load), if we didn't start in hyp mode then log a useful message telling the user why KVM isn't available

**Comment by chazy** [comment]
Hi Peter,

I'd love to include this in the next patch series, but could you refresh my memory. I believe Dave Martin had some patches floating around for saving the backdoor - do you know what the status is here and if they're being merges somewhere or at least a concensus has been reached? (I can get in touch with him otherwise).

Alternatively we can put something short-and-sweet to just fix KVM that we can rip out later when the other patches mature that allows us to run the same kernel on both host / guest?

**Comment by pm215** [comment]
On 28 May 2012 17:22, Christoffer Dall
reply@reply.github.com
wrote:

> Hi Peter,
> 
> I'd love to include this in the next patch series, but could you refresh my memory. I believe Dave Martin had some patches floating around for saving the backdoor - do you know what the status is here and if they're being merges somewhere or at least a concensus has been reached? (I can get in touch with him otherwise).

I think he did, but I can't remember the status either -- best
to email him directly I think.

-- PMM

**Comment by chazy** [comment]
This was done a while ago, let's not have these lingering around.
